# Generated by Django 2.0.4 on 2018-05-16 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thoughts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('condition', models.IntegerField(choices=[(0, 'Ecstatic'), (5, 'Passionate'), (10, 'Happy'), (15, 'Bored'), (20, 'Pessimistic'), (25, 'Frustated'), (26, 'Tired'), (27, 'Hungry'), (30, 'Disappointed'), (35, 'Pessimistic'), (40, 'Angry'), (45, 'Guilty'), (50, 'Fear'), (55, 'Grief'), (60, 'Despair'), (65, 'Jealous'), (70, 'Pessimistic'), (75, 'Worried')])),
                ('notes', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thoughts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
